# start screen before qrsh ex. screen -S nameIwant
# check cluster resources  qpic -q bluejay
#spatialDLPFC $ qrsh -l bluejay,mem_free=150G,h_vmem=150G
#~ $ cd /dcs04/lieber/lcolladotor/spatialDLPFC_LIBD4035/spatialDLPFC
# R



## This script requires R 4.1
# module load conda_R/devel

## utils
library("here")
library("sessioninfo")
library("pryr")

## reading the data
library("SpatialExperiment")
library("rtracklayer")

## vis
library("spatialLIBD")

## analysis
library("scran") ## requires uwot for UMAP
library("scater")
library("BiocParallel")
library("PCAtools")
library(ggplot2)
library(harmony)
library(BayesSpace)
library(patchwork)

#If you want to make downsampled version of spe object 
# if(spatialData(spe)$array_col < 64 & spatialData(spe)$array_row < 39) {
#   spe$quadrant<-"topleft"} else if(spatialData(spe)$array_col >= 64 & spatialData(spe)$array_row < 39){
#   spe$quadrant<-"topright"}else if(spatialData(spe)$array_col < 64 & spatialData(spe)$array_row >= 39){
#   spe$quadrant<-"bottomleft"}else if(spatialData(spe)$array_col >= 64 & spatialData(spe)$array_row >= 39){
#   spe$quadrant<-"bottomright"}else{
#   spe$quadrant<-"NA"}
# 
# 
# spe$sample_quadrant <- paste0(spe$sampleid, "_", spe$quadrant)
# sample_quad_list <- rafalib::splitit(spe$sample_quadrant)
# selected_sample_quad <- unlist(lapply(sample_squad_list, sample, n = 250))
# spe_subsampled <- spe[, selected_sample_quad]

load(file = here::here("processed-data","rdata","spe","spe_final.Rdata"))

#put harmony batch correction here. Do we want to use the PCs we generated or the ones generated by spatial pre-process?
spe = spatialPreprocess(spe, n.PCs = 50)
spe = runUMAP(spe, dimred = "PCA")
colnames(reducedDim(spe, "UMAP")) = c("UMAP1", "UMAP2")

pdf(file=here::here("plots","UMAP_subject.pdf"))
ggplot(data.frame(reducedDim(spe, "UMAP")), 
       aes(x = UMAP1, y = UMAP2, color = factor(spe$subject))) +
  geom_point() +
  labs(color = "Subject") +
  theme_bw()
dev.off()

spe = RunHarmony(spe, "subject", verbose = F)
spe = runUMAP(spe, dimred = "HARMONY", name = "UMAP.HARMONY")
colnames(reducedDim(spe, "UMAP.HARMONY")) = c("UMAP1", "UMAP2")

save(spe, file = here::here("processed-data","rdata","spe","spe_final.Rdata"))

pdf(file=here::here("plots","UMAP_harmony_subject.pdf"))
ggplot(data.frame(reducedDim(spe, "UMAP.HARMONY")), 
       aes(x = UMAP1, y = UMAP2, color = factor(spe$subject))) +
  geom_point() +
  labs(color = "Subject") +
  theme_bw()
dev.off()

auto_offset_row <- as.numeric(factor(unique(spe$sample_id))) * 100
names(auto_offset_row) <-unique(spe$sample_id)
spe$row <- spatialData(spe)$array_row + auto_offset_row[spe$sample_id]
spe$col <- spatialData(spe)$array_col

summary(colData(spe)$row)
summary(colData(spe)$col)

pdf(file= here::here("plots","bayesSpace_offset_check.pdf"))
clusterPlot(spe, "subject", color = NA) + #make sure no overlap between samples
  labs(fill = "Subject", title = "Offset check")
dev.off()

spe = spatialCluster(spe, use.dimred = "HARMONY", q = 7, nrep = 10000) #use HARMONY
#spe = spatialCluster(spe, use.dimred = "HARMONY", q = 14, nrep = 10000)

#save(spe, file = "/dcs04/lieber/lcolladotor/spatialDLPFC_LIBD4035/spatialDLPFC/processed-data/rdata/pilot_dlpfc_data/spe_pilot_102121.Rdata")
save(spe, file = here::here("processed-data","rdata","spe","spe_final.Rdata"))


#####stop here 11/2/21

Sys.time()
g_k10 <- buildSNNGraph(spe, k = 10, use.dimred = 'PCA')
Sys.time()
## About 12 minutes
# [1] "2019-11-13 15:20:32 EST"
# [1] "2019-11-13 15:31:50 EST"
save(g_k10, file=here::here("processed-data", "rdata","spe","g_k10.Rdata"))

Sys.time()
g_walk_k10 <- igraph::cluster_walktrap(g_k10)
Sys.time()
save(g_walk_k10, file = here::here("processed-data", "rdata","spe","g_walk_k10.Rdata"))

clust_k10 <- sort_clusters(g_walk_k10$membership)
save(clust_k10, file = here::here("processed-data", "rdata","spe","clust_k10.Rdata"))
#finished in 4.5 hours

### For the SNN graph with K = 50, find which nested subset best matches
## the clusters from 10x Genomics labeled by Kristen Maynard and Keri Martinowich
clust_k5_list <- lapply(4:28, function(n) {
  message(paste(Sys.time(), 'n =', n))
  sort_clusters(igraph::cut_at(g_walk_k10, n = n))
})
names(clust_k5_list) <- paste0('k', 4:28)
save(clust_k5_list, file = here::here("processed-data", "rdata", "clust_k5_list.Rdata"))

## Add clusters to spe colData
col.names <- paste0("SNN_k10_k",4:28)
for (i in seq_along(col.names)){
  colData(spe) <- cbind(colData(spe),clust_k5_list[i])
}
colnames(colData(spe))[19:43] <- col.names

save(spe, file = here::here("processed-data", "rdata","spe", "spe_snn_clusters.Rdata"))




